apiVersion: v1
kind: Service
metadata:
  name: prestashop-service
  namespace: 4k8s
spec:
  type: NodePort
  selector:
    app: prestashop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

